"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { type ReactNode, useEffect, useState } from "react";
import { SkeletonImg } from "@/components/media/skeleton-media";
import { Amount } from "@/components/ui/amount";
import { Button, ButtonLink, buttonClass } from "@/components/ui/button";
import { Compare } from "@/components/ui/compare";
import { Tag } from "@/components/ui/tag";
import { formatCredits } from "@/lib/credits/format";
import type { LogEntry } from "@/lib/log/entries";
import { ROUTES } from "../routes";
import { LocalTime } from "./local-time";
import { PublishControl } from "./publish-control";

// One run, on the record: the media at full size, then everything that happened. Balance-after
// is the owner's business, so a public viewer never sees it.
export function RunRecord({ initial, registered }: { initial: LogEntry; registered: boolean }) {
  const router = useRouter();
  const [e, setE] = useState(initial);
  const [copied, setCopied] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const running = e.status === "queued" || e.status === "processing";

  useEffect(() => {
    if (!running) return;
    const t = setInterval(async () => {
      const res = await fetch(`/api/log/${e.id}`, { cache: "no-store" });
      if (res.ok) setE((await res.json()).entry);
    }, 1500);
    return () => clearInterval(t);
  }, [running, e.id]);

  const video = e.vertical === "video";
  const take = e.assets.find((a) => a.kind === "video");
  const images = e.assets.filter((a) => a.kind === "image");
  const first = take ?? images[0];
  const library = e.type === "library";
  const failed = e.status === "failed" || e.status === "canceled";
  const outputGone = !running && !failed && e.assets.length === 0;
  const title = video ? (e.presetName ?? "Camera move") : e.prompt;
  const took = e.finishedAt && !library ? (new Date(e.finishedAt).getTime() - new Date(e.createdAt).getTime()) / 1000 : null;

  async function deleteOutput() {
    if (!confirmDelete) return setConfirmDelete(true);
    setDeleting(true);
    const res = await fetch(`/api/log/${e.id}`, { method: "DELETE" });
    if (res.ok) setE({ ...e, assets: [], published: false });
    setDeleting(false);
    setConfirmDelete(false);
    router.refresh();
  }

  return (
    <main className="mx-auto grid w-full max-w-[1200px] gap-8 px-4 py-6 sm:py-8 lg:grid-cols-[minmax(0,1fr)_360px] lg:gap-12">
      <section aria-label="The output" className="min-w-0">
        {running ? (
          <div className="relative w-full overflow-hidden rounded-xl" style={{ aspectRatio: String(e.params?.aspect ?? "1:1").replace(":", " / "), maxHeight: "70vh" }}>
            <div className="skeleton skeleton-live absolute inset-0" />
            <p className="t-body absolute inset-x-4 bottom-4 font-medium">
              {video ? "Rendering the move" : "Making the image"}, {e.progress}%
            </p>
          </div>
        ) : failed || outputGone ? (
          <div className="flex min-h-48 flex-col justify-center gap-2 rounded-xl bg-field p-6">
            <p className="t-title">{outputGone ? "The output was deleted" : e.status === "canceled" ? "This run was stopped" : "This run failed"}</p>
            <p className="t-body text-muted">{outputGone ? "Its owner deleted what it made. The run stays on the record, with what it cost." : e.status === "canceled" ? "Nothing was made, and the credits went back." : e.errorMessage}</p>
          </div>
        ) : video && take && e.renderedFrom ? (
          <Compare
            still={{ url: e.renderedFrom.url, alt: e.renderedFrom.prompt ?? "The still" }}
            take={{ url: take.url, posterUrl: take.posterUrl, label: `${title} rendered over the still` }}
            width={take.width}
            height={take.height}
            stillLabel={e.servedAs === "prerendered" ? "Library still" : "Still"}
          />
        ) : images.length ? (
          <div className={images.length > 1 ? "grid grid-cols-2 gap-2" : ""}>
            {images.map((a) => (
              <SkeletonImg key={a.id} src={a.url} alt={e.prompt} className="w-full rounded-xl object-contain" style={{ aspectRatio: `${a.width} / ${a.height}`, maxHeight: images.length > 1 ? undefined : "78vh" }} />
            ))}
          </div>
        ) : null}
      </section>

      <aside aria-label="The record" className="flex flex-col gap-5 lg:sticky lg:top-20 lg:self-start">
        <div className="flex flex-col gap-2">
          <div className="flex flex-wrap gap-2">
            {library ? <Tag>From the library</Tag> : e.servedAs === "prerendered" ? <Tag tone="outline">Pre-rendered example</Tag> : video ? <Tag>Rendered with ffmpeg</Tag> : <Tag>Generated by {e.modelName}</Tag>}
            {!e.mine && !library && <Tag tone="ink">Public</Tag>}
          </div>
          <h1 className="t-title">{title}</h1>
          {video && <p className="t-meta">{e.servedAs === "prerendered" ? "A pre-rendered example of this move, over a library still. Live rendering is capped on this free-tier deployment; nothing was charged." : "A real camera move rendered frame by frame over the still, not generated by a video model."}</p>}
        </div>

        <dl className="flex flex-col gap-3 rounded-xl bg-field p-4 text-[0.9375rem]">
          <Row label="Model">{e.modelName}</Row>
          {video && e.servedAs === "prerendered" && e.inputAsset && <Row label="You chose">{e.inputAsset.prompt ?? "Your image"}</Row>}
          {video && e.renderedFrom && <Row label="Rendered over">{e.renderedFrom.prompt ?? "The still"}</Row>}
          {e.params?.aspect ? <Row label="Aspect">{String(e.params.aspect)}</Row> : null}
          {first && <Row label="Size">{`${first.width} by ${first.height}${first.durationMs ? `, ${Math.round(first.durationMs / 1000)} seconds` : ""}`}</Row>}
          {took !== null && took > 0.05 && <Row label="Took">{took < 10 ? `${took.toFixed(1)} seconds` : `${Math.round(took)} seconds`}</Row>}
          <Row label={library ? "Added" : "Made"}>
            <LocalTime iso={e.createdAt} withDate />
          </Row>
          {!library && (
            <Row label="Cost">
              <Amount tenths={e.settlement === "refunded" ? e.refundedTenths : e.chargedTenths} as={e.settlement} />
            </Row>
          )}
          {e.mine && e.balanceAfterTenths !== null && <Row label="Balance after">{`${formatCredits(e.balanceAfterTenths)} credits`}</Row>}
        </dl>

        {e.mine && !running && !failed && !outputGone && <PublishControl id={e.id} published={e.published} registered={registered} />}

        <div className="flex flex-wrap gap-2">
          {first && !running && (
            <a href={first.url} download className={buttonClass("secondary", "sm")}>
              Download
            </a>
          )}
          {images[0] && (e.mine || library) && <ButtonLink href={`${ROUTES.make}?still=${images[0].id}`} size="sm">Move the camera over this</ButtonLink>}
          {!video && e.prompt && (
            <Link href={`${ROUTES.make}?prompt=${encodeURIComponent(e.prompt)}`} className={buttonClass("secondary", "sm")}>
              Make one like this
            </Link>
          )}
          {(e.published || library) && (
            <Button
              size="sm"
              variant="quiet"
              onClick={async () => {
                await navigator.clipboard.writeText(window.location.href);
                setCopied(true);
                setTimeout(() => setCopied(false), 2000);
              }}
            >
              {copied ? "Link copied" : "Copy link"}
            </Button>
          )}
        </div>

        {e.mine && !running && e.assets.length > 0 && (
          <div className="flex flex-col items-start gap-1.5 border-t border-line pt-4">
            <Button size="sm" variant={confirmDelete ? "danger" : "quiet"} onClick={deleteOutput} pending={deleting}>
              {confirmDelete ? "Delete it" : "Delete the output"}
            </Button>
            <p className="t-meta">{confirmDelete ? "This removes the output and takes it off the public log. The run stays on the record." : "The run stays on the record, with what it cost."}</p>
          </div>
        )}
        <Link href={e.mine ? ROUTES.log : ROUTES.make} className="t-meta underline underline-offset-2 hover:text-ink">
          {e.mine ? "Back to your log" : "Make your own"}
        </Link>
      </aside>
    </main>
  );
}

function Row({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div className="flex flex-col gap-0.5">
      <dt className="t-label text-muted">{label}</dt>
      <dd className="min-w-0">{children}</dd>
    </div>
  );
}
