import Link from "next/link";
import { LoopingVideo } from "@/components/media/looping-video";
import { SkeletonImg } from "@/components/media/skeleton-media";
import { Amount } from "@/components/ui/amount";
import { ButtonLink } from "@/components/ui/button";
import { Compare } from "@/components/ui/compare";
import { formatCredits } from "@/lib/credits/format";
import type { HomeData } from "@/lib/docket/home-data";
import type { LogEntry } from "@/lib/log/entries";
import { truncateWords } from "@/lib/text";
import { ImageAllowance } from "../make/composer";
import { ROUTES } from "../routes";
import { runTitle } from "@/lib/log/titles";

// Home explains; /make makes; /log remembers. Top to bottom: what Docket is and who it's for,
// the one way in (above the fold at 390 and 1440), the real still-and-move pair, how it works (each step a real artifact from one published run),
// what's real, what's free, one way in, and a short strip of the public log.
// Every number here comes from HomeData, which reads it from the database or the enforced values.
export function HomePage({ data: d, signedIn, registered, balanceTenths, liveRendersWithAccount }: { data: HomeData; signedIn: boolean; registered: boolean; balanceTenths: number | null; liveRendersWithAccount: number }) {
  const allowance = Math.min(d.quota.siteLeft, d.quota.yoursLeft);
  const outOfImages = allowance === 0;
  const moves = (n: number) => `${n} live camera ${n === 1 ? "move" : "moves"}`;

  return (
    <main className="mx-auto flex w-full max-w-[1200px] flex-col gap-14 px-4 py-8 sm:gap-20 sm:py-12">
      <section aria-labelledby="home-heading" className="flex flex-col gap-6">
        <div className="flex max-w-3xl flex-col gap-3">
          <h1 id="home-heading" className="t-display">
            Docket makes an image, then moves the camera over it.
          </h1>
          <p className="t-body text-muted" data-testid="home-for">
            For anyone who wants a moving shot from a single picture: describe an image, pick one of {d.moveCount} camera moves, and get a {d.move.seconds}-second {d.move.resolution} clip, with every credit accounted for.
          </p>
        </div>
        {outOfImages ? (
          // Out of today's images: lead with what still works, and say why second.
          <div className="flex max-w-md flex-col gap-3" data-testid="home-actions">
            <ButtonLink href={`${ROUTES.make}?mode=move`} size="lg">
              Move the camera over a library image
            </ButtonLink>
            <ImageAllowance quota={d.quota} />
            <ButtonLink href={ROUTES.publicLog} variant="secondary" size="lg">
              See the public log
            </ButtonLink>
          </div>
        ) : (
          <div className="flex flex-col gap-3 sm:flex-row" data-testid="home-actions">
            <ButtonLink href={ROUTES.make} size="lg">
              Start making
            </ButtonLink>
            <ButtonLink href={ROUTES.publicLog} variant="secondary" size="lg">
              See the public log
            </ButtonLink>
          </div>
        )}
        {d.pair && (
          // Capped so the pair never grows past the first screen's worth of height.
          <figure className="flex flex-col gap-2" style={{ width: `min(100%, 960px, calc(58svh * ${d.pair.take.width} / ${d.pair.take.height}))` }} data-testid="home-pair">
            <Compare
              still={{ url: d.pair.still.url, alt: d.pair.still.prompt ?? "The still" }}
              take={{ url: d.pair.take.url, posterUrl: d.pair.take.posterUrl, label: `${d.pair.presetName}, rendered over the still` }}
              width={d.pair.take.width}
              height={d.pair.take.height}
              stillLabel="Library still"
              hint="Drag to compare"
            />
            <figcaption className="t-meta">{d.pair.presetName}, rendered with ffmpeg over a library still.</figcaption>
          </figure>
        )}
      </section>

      <section aria-labelledby="how-heading" className="flex flex-col gap-6" data-testid="how-it-works">
        <h2 id="how-heading" className="t-title">
          How it works
        </h2>
        <HowItWorks example={d.example} image={d.image} moveCount={d.moveCount} />
      </section>

      <section aria-labelledby="real-heading" className="flex max-w-3xl flex-col gap-4" data-testid="whats-real">
        <h2 id="real-heading" className="t-title">
          What&apos;s real
        </h2>
        <ul className="t-body flex list-disc flex-col gap-2 pl-5">
          <li>
            Images are generated by {d.image.name} on {d.image.provider}.
          </li>
          <li>Camera moves are rendered with ffmpeg over the still, frame by frame. They are not AI video.</li>
          <li>
            Every credit in and out is recorded, with the balance after it.{" "}
            <Link href={d.example ? ROUTES.entry(d.example.id) : ROUTES.publicLog} className="inline-block py-2 font-medium underline underline-offset-2 hover:text-muted" data-testid="proof-link">
              See a real run&apos;s record
            </Link>
          </li>
        </ul>
      </section>

      <section aria-labelledby="free-heading" className="flex max-w-3xl flex-col gap-5" data-testid="free-to-start">
        <div className="flex flex-col gap-2">
          <h2 id="free-heading" className="t-title">
            Free to start
          </h2>
          <p className="t-body" data-testid="starter">
            {signedIn && balanceTenths !== null ? `You have ${formatCredits(balanceTenths)} credits.` : `No account needed: you start with ${formatCredits(d.starterTenths)} free credits.`} An image costs {formatCredits(d.image.costTenths)} and a live camera move {formatCredits(d.move.costTenths)}.
          </p>
          <p className="t-body" data-testid="daily-limits">
            You can make up to {d.quota.perVisitor} images a day, from {d.quota.siteCapacity} a day shared by everyone on this deployment, and {moves(d.liveRenders)}
            {!registered && liveRendersWithAccount !== d.liveRenders ? ` (${liveRendersWithAccount} with an account)` : ""}. After that, camera moves come as pre-rendered examples, free.
          </p>
        </div>
      </section>

      {d.strip.length > 0 && (
        <section aria-labelledby="strip-heading" className="flex flex-col gap-4" data-testid="public-strip">
          <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
            <h2 id="strip-heading" className="t-title">
              From the public log
            </h2>
            <Link href={ROUTES.publicLog} className="t-meta inline-block py-2 underline underline-offset-2 hover:text-ink">
              See all of it
            </Link>
          </div>
          <ul className="grid grid-cols-2 gap-x-4 gap-y-6 md:grid-cols-4">
            {d.strip.map((e) => (
              <StripItem key={e.id} entry={e} />
            ))}
          </ul>
        </section>
      )}
    </main>
  );
}

function HowItWorks({ example: e, image, moveCount }: { example: LogEntry | null; image: HomeData["image"]; moveCount: number }) {
  const still = e?.renderedFrom ?? null;
  const take = e?.assets.find((a) => a.kind === "video") ?? null;
  // Tall 9:16 frames stay narrow instead of taking over the page.
  const box = take ? { aspectRatio: `${take.width} / ${take.height}`, width: `min(100%, ${Math.round((360 * take.width) / take.height)}px)` } : { aspectRatio: "1 / 1" };
  return (
    <ol className="grid gap-8 md:grid-cols-3 md:gap-6">
      <li className="flex flex-col gap-3">
        <div className="flex flex-col gap-1">
          <h3 className="t-label text-[0.9375rem]">1. Make an image</h3>
          <p className="t-body text-muted">Describe it, and {image.name} makes it.</p>
        </div>
        {still && (
          <figure className="flex flex-col gap-2">
            <SkeletonImg src={still.url} alt={still.prompt ?? "A still from the library"} className="w-full rounded-xl object-cover" style={box} />
            {still.prompt && <figcaption className="t-meta">&ldquo;{truncateWords(still.prompt, 90)}&rdquo;</figcaption>}
          </figure>
        )}
      </li>
      <li className="flex flex-col gap-3">
        <div className="flex flex-col gap-1">
          <h3 className="t-label text-[0.9375rem]">2. Choose a camera move</h3>
          <p className="t-body text-muted">Pick one of the {moveCount}, and ffmpeg renders it over your image.</p>
        </div>
        {take && e && (
          <figure>
            <LoopingVideo src={take.url} poster={take.posterUrl} label={`${e.presetName ?? "Camera move"}, rendered live over that still`} className="w-full rounded-xl bg-field object-cover" style={box} />
          </figure>
        )}
      </li>
      <li className="flex flex-col gap-3">
        <div className="flex flex-col gap-1">
          <h3 className="t-label text-[0.9375rem]">3. Every run stays on the record</h3>
          <p className="t-body text-muted">What you asked for, the model that ran, what it cost, and any refund.</p>
        </div>
        {e && <Receipt entry={e} />}
      </li>
    </ol>
  );
}

// The run's receipt line, as its record shows it.
function Receipt({ entry: e }: { entry: LogEntry }) {
  return (
    <div className="flex flex-col gap-3 rounded-xl bg-field p-4" data-testid="home-receipt">
      <dl className="grid grid-cols-[auto_1fr] gap-x-4 gap-y-2 text-[0.9375rem]">
        <dt className="text-muted">Model</dt>
        <dd className="font-medium">{e.modelName}</dd>
        {e.presetName && (
          <>
            <dt className="text-muted">Move</dt>
            <dd className="font-medium">{e.presetName}</dd>
          </>
        )}
        <dt className="text-muted">Cost</dt>
        <dd>
          {e.settlement === "free" ? <Amount tenths={0} as="free" /> : <Amount tenths={e.costTenths} as="charged" />}
          {e.servedAs === "prerendered" && <span className="t-meta"> (a pre-rendered example)</span>}
        </dd>
        <dt className="text-muted">Refund</dt>
        <dd>{e.refundedTenths > 0 ? <Amount tenths={e.refundedTenths} as="refunded" /> : e.settlement === "free" ? "None: nothing was charged" : "None"}</dd>
      </dl>
      <Link href={ROUTES.entry(e.id)} className="t-meta inline-block self-start py-2 underline underline-offset-2 hover:text-ink">
        Open this run&apos;s record
      </Link>
    </div>
  );
}

function StripItem({ entry: e }: { entry: LogEntry }) {
  const take = e.assets.find((a) => a.kind === "video");
  const img = e.assets.find((a) => a.kind === "image");
  const src = take ? take.posterUrl : img?.url;
  const title = runTitle(e);
  return (
    <li>
      <Link href={ROUTES.entry(e.id)} className="group flex flex-col gap-2 rounded-xl">
        <span className="block aspect-square overflow-hidden rounded-xl bg-field">{src && <SkeletonImg src={src} alt="" className="h-full w-full object-cover" />}</span>
        <span className="line-clamp-2 text-[0.9375rem] font-medium group-hover:underline">{title}</span>
        <span className="t-meta">{e.type === "library" ? `Library image, ${e.modelName}` : e.servedAs === "prerendered" ? "Pre-rendered example" : e.servedAs === "live" ? "Rendered live with ffmpeg" : e.modelName}</span>
      </Link>
    </li>
  );
}
