import { notFound } from "next/navigation";
import { formatCredits } from "@/lib/credits/format";
import { frameDataUri, OG_SIZE, shareCard } from "@/lib/og/card";
import { getLogEntry } from "@/lib/log/entries";
import { truncateWords } from "@/lib/text";
import { runTitle } from "@/lib/log/titles";

export const size = OG_SIZE;
export const contentType = "image/png";
export const alt = "A run on Docket";

// The share image for a run, made from the run: its image, or for a camera move the take's
// poster frame. (Not the still beside it: a take's first frame is the still, so the pair read as
// a duplicate at preview size.) Visible to link previews only for public runs, the same
// rule as the page: a private or missing run is a 404 here too.
export default async function Image({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const e = await getLogEntry(id, null);
  if (!e || (e.type === "run" && !e.published)) notFound();
  const take = e.assets.find((a) => a.kind === "video");
  const image = e.assets.find((a) => a.kind === "image");
  const frames = [await frameDataUri(take ? take.posterUrl : image?.url)];
  const title = truncateWords(runTitle(e), 70);
  const lines =
    e.type === "library"
      ? [`Made with ${e.modelName} for Docket's public library.`]
      : take
        ? [
            e.servedAs === "prerendered" ? "A pre-rendered example of this camera move, over a library still." : "A real camera move, rendered with ffmpeg over the still.",
            e.settlement === "free" ? "Free: nothing was charged." : `${formatCredits(e.chargedTenths)} credits charged.`,
          ]
        : [`Generated by ${e.modelName}.`, e.settlement === "refunded" ? "Refunded." : `${formatCredits(e.chargedTenths)} credits charged.`];
  return shareCard({ frames, title, lines });
}
