import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { RunRecord } from "@/components/docket/log/record";
import { getCurrentUser } from "@/lib/auth/current-user";
import { getLogEntry } from "@/lib/log/entries";
import { truncateWords } from "@/lib/text";

// A run's permanent link. The owner always sees it; anyone else, signed in or not, only if it
// was published (or it's a library item). Otherwise it's a plain 404, which doesn't reveal
// whether a private run exists.
export async function generateMetadata({ params }: PageProps<"/log/[id]">): Promise<Metadata> {
  const { id } = await params;
  const user = await getCurrentUser();
  const e = await getLogEntry(id, user?.id ?? null);
  if (!e) return { title: "Not found", robots: { index: false } };
  const video = e.vertical === "video";
  const title = truncateWords(video ? (e.presetName ?? "Camera move") : e.prompt, 60);
  const description =
    e.type === "library"
      ? `An image made with ${e.modelName} for Docket's public library.`
      : video
        ? e.servedAs === "prerendered"
          ? `A pre-rendered example of the ${e.presetName ?? "camera"} move over a library still, on Docket.`
          : `A camera move rendered with ffmpeg over the still, on Docket.`
        : `Generated by ${e.modelName} from this prompt: ${truncateWords(e.prompt, 140)}`;
  // Previews are for runs anyone can see. The share image (opengraph-image.tsx) follows the same
  // rule and is a 404 for a private run.
  const shareable = e.published || e.type === "library";
  return {
    title,
    description,
    robots: shareable ? undefined : { index: false },
    openGraph: shareable ? { title, description, type: "article", siteName: "Docket", url: `/log/${e.id}` } : undefined,
    twitter: shareable ? { card: "summary_large_image", title, description } : undefined,
  };
}

export default async function Entry({ params }: PageProps<"/log/[id]">) {
  const { id } = await params;
  const user = await getCurrentUser();
  const entry = await getLogEntry(id, user?.id ?? null);
  if (!entry) notFound();
  return <RunRecord initial={entry} registered={user?.kind === "registered"} />;
}
