import type { ReactNode } from "react";

// Small labels for what something is: "Generated by FLUX.1 [schnell]", "Pre-rendered example",
// "Private". Always words; tone only reinforces.
type Tone = "plain" | "outline" | "live" | "ink";
const TONE: Record<Tone, string> = {
  plain: "bg-field text-ink",
  outline: "border border-ink/25 text-ink",
  live: "bg-live/10 text-live",
  ink: "bg-ink text-paper",
};

export function Tag({ tone = "plain", children, className = "" }: { tone?: Tone; children: ReactNode; className?: string }) {
  return <span className={`inline-flex h-6 items-center rounded-md px-2 text-[0.75rem] font-semibold ${TONE[tone]} ${className}`}>{children}</span>;
}
